### ISSUE TITLE
Setup/Install/Use instructions

### ISSUE THREAD

**Issue by ghost** [Harl-Towne/event-camera-vpr-demonstrator#6]
Make a readme with instructions for installing and using the demo.

**Comment by Tobias-Fischer** [comment]
Please add a launch file to easily launch the different nodes, and change the readme.

**Comment by ghost** [comment]
> 

I've got a couple of launch files, did you want me to add a launch file for each node?

**Comment by Tobias-Fischer** [comment]
No, one launch file that starts all useful nodes together so multiple terminals aren't needed

**Comment by Tobias-Fischer** [comment]
Ah you already have them - please move them in a `launch` folder and install them in the CMakeLists.txt.
